services:
    # docker compose up -d --build

    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        container_name: php
        build: .docker/php
        ports:
            - 5173:5173
        tty: true
        volumes:
            - ./src:${DIR}:cached
        restart: unless-stopped
        networks:
            - net

    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - 80:80
        tty: true
        volumes:
            - ./src:${DIR}
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - reverb
            - php
        restart: unless-stopped
        networks:
            - net

    ####################################################################################################
    # reverb
    ####################################################################################################
    reverb:
        container_name: reverb
        build: .docker/php
        ports:
            - '8080:8080'
        volumes:
            - ./src:${DIR}
        working_dir: ${DIR}
        depends_on:
            - db
            - redis
        restart: unless-stopped
        networks:
            - net
        command: 'php artisan reverb:start --debug'

    ####################################################################################################
    # Supervisor
    ####################################################################################################
    supervisor:
        build: .docker/php
        container_name: supervisor
        user: root
        volumes:
            - ./src:${DIR}
        working_dir: ${DIR}
        depends_on:
            - php
        restart: unless-stopped
        networks:
            - net
        command: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf

    ####################################################################################################
    # DATABASE (MySQL)
    ####################################################################################################

    db:
        container_name: db
        image: mysql:latest
        tty: true
        volumes:
            - .docker/db/data:/var/lib/mysql
            - .docker/logs:/var/log/db
            - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - .docker/db/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        restart: unless-stopped
        networks:
            - net

    db_test:
        image: mysql:latest
        container_name: db_test
        restart: unless-stopped
        tty: true
        command: --innodb_use_native_aio=0
        volumes:
            - .docker/db_test/data:/var/lib/mysql
            - .docker/logs:/var/log/db_test
            - .docker/db_test/my.cnf:/etc/mysql/conf.d/my.cnf
            - .docker/db_test/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_TEST_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_TEST_DATABASE}
            MYSQL_USER: ${DB_TEST_USER}
            MYSQL_PASSWORD: ${DB_TEST_PASSWORD}
        networks: 
            - net

    ####################################################################################################
    # phpMyAdmin
    ####################################################################################################
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - 8081:80
        tty: true
        links:
            - db
            - db_test
        environment:
            PMA_HOSTS: db,db_test
            PMA_PORTS: 3306
            #PMA_ARBITRARY: 1
        volumes:
            - .docker/phpmyadmin/sessions:/sessions
        restart: unless-stopped
        networks:
            - net

    ####################################################################################################
    # Mailpit
    ####################################################################################################
    mail:
        container_name: mailpit
        image: axllent/mailpit:latest
        ports:
            - 8025:8025
            - 1025:1025
        tty: true
        restart: unless-stopped
        networks:
            - net

    ####################################################################################################
    # Redis
    ####################################################################################################
    redis:
        container_name: redis
        image: redis:latest
        command: redis-server --appendonly yes
        volumes:
            - .docker/redis/data:/data
        tty: true
        ports:
            - 6379:6379
        restart: unless-stopped
        networks:
            - net

#Networks
networks:
  net: